__use_yte__: true
executor: slurm
default-resources:
  slurm_account: acqtjvjc9x
  slurm_partition: wzacnormal
  nodes: 1
  mem_mb: attempt * 1024 * 50
jobs: 10
latency-wait: 120
use-conda: True
keep-going: True
rerun-incomplete: True
